//! River Gateway - Agent Runtime

pub mod adapters;
pub use adapters::AdapterRegistry;
pub mod config;
pub mod db;
pub mod session;
pub mod tools;
pub mod state;
pub mod server;
pub mod api;
pub mod r#loop;
pub mod memory;
pub mod redis;
pub mod heartbeat;
pub mod git;
pub mod inbox;
pub mod conversations;
pub mod subagent;
pub mod metrics;
pub mod logging;
pub mod policy;
pub mod preferences;
pub mod watchdog;
pub mod embeddings;
pub mod flash;
pub mod agent;
pub mod coordinator;
pub mod spectator;
